name: Docker Image CI
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Build the Docker image
        env:
          USER: ${{ secrets.DOCKER_USER }}
          PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker build -t musddik/flask-server-demo-2026:v1 .
         
      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
 
      - name: Push Docker image to Docker Hub
        run: |
          docker push musddik/flask-server-demo-2026:v1
